# Generated by Django 3.2.2 on 2021-05-14 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_country_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='educational_sector',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
