# Generated by Django 3.2.3 on 2021-05-21 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_auto_20210514_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educational_sector',
            options={'ordering': ['name'], 'verbose_name': 'Education Sector', 'verbose_name_plural': 'Educational Sectors'},
        ),
    ]
