# Generated by Django 3.2.3 on 2021-05-25 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_alter_educational_sector_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='tel',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='coordinator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='web.coordinator'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(unique=True),
        ),
    ]
