# Generated by Django 3.2.3 on 2021-05-25 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_auto_20210525_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='coordinator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.coordinator'),
        ),
    ]
