# Generated by Django 3.2.3 on 2021-05-26 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_auto_20210525_1143'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='educational_sector',
            options={'ordering': ['name'], 'verbose_name': 'Educational Sector', 'verbose_name_plural': 'Educational Sectors'},
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='coordinator',
            name='tel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='school',
            name='category',
        ),
        migrations.AddField(
            model_name='school',
            name='category',
            field=models.ManyToManyField(blank=True, to='web.category'),
        ),
        migrations.AlterField(
            model_name='school',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='tel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='website',
            field=models.URLField(null=True),
        ),
    ]
