# Generated by Django 3.2.3 on 2021-06-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_alter_school_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='email',
            field=models.TextField(blank=True, null=True),
        ),
    ]
